name: Centralized Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
    
  call-nodejs-workflow:
    uses:
      sindhura530/ActionWorkflows/.github/workflows/nodejs.yml@main
    
  Build-artifacts:
    needs: [call-nodejs-workflow]
    runs-on: ubuntu-latest
    steps:
      - name: 'finding path'
        run: readlink -f downloads
      - name: Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v2
        with: 
          name: download_file
          path: sindhura530/ActionWorkflows/.github/workflows/nodejs.yml
    
    
    
      
  call-maven-workflow:
    uses:
      sindhura530/ActionWorkflows/.github/workflows/maven.yml@main
      
  call-python-workflow:
    uses:
      sindhura530/ActionWorkflows/.github/workflows/python.yml@main
      
      
      
      
  
   
      
  
