name: Centralized Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
    
  call-nodejs-workflow:
    uses:
      sindhura530/ActionWorkflows/.github/workflows/nodejs.yml@main
    
  Build-artifacts:
    needs: [call-nodejs-workflow]
    runs-on: ubuntu-latest
    steps:

      - name: Create a temporary artifact downloads folder
        run: mkdir downloads
        
      - name: Add artifacts to publish to the temp folder
        run: |
          cd downloads
          echo 'sindhu'    > sindhu.html
          echo 'chaitra'    > chaitra.html
          echo 'ramya'  > ramya.html
          cd ..
    
      - name: Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v2
        with: 
          name: assets-for-download
          path: downloads
    
    
    
      
  call-maven-workflow:
    uses:
      sindhura530/ActionWorkflows/.github/workflows/maven.yml@main
      
  call-python-workflow:
    uses:
      sindhura530/ActionWorkflows/.github/workflows/python.yml@main
      
      
      
      
  
   
      
  
