name: Centralized Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
    
  call-nodejs-workflow:
    uses:
      sindhura530/ActionWorkflows/.github/workflows/nodejs.yml@main
   
      
  
