name: maven

on: 
  workflow_call:
  
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11, 12, 13 ]
    
    steps:
      - uses: actions/checkout@v3
      - name: Use java ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java: ${{ matrix.java }}
  
