name: NodeJS

on: 
  workflow_call:
  
jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [10.x, 8.x]
    
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Create a temporary artifact downloads folder
      run: mkdir downloads
        
    - name: Add artifacts to publish to the temp folder
      run: |
          cd downloads
          echo 'sindhu'    > sindhu.html
          echo 'chaitra'    > chaitra.html
          echo 'ramya'  > ramya.html
          cd ..


    
  
